### ISSUE TITLE
Request: Add a quantity field alongside each item placed into the "Cargo Hold" tab of Vehicle and Starship "actor" cards

### ISSUE THREAD

**Issue by UniqueUser97** [algnc/od6s-star-wars#13]
Firstly, thanks for the awesome SW D6 sheets module for FoundryVTT.

I'm building up a roster of “actors” and noticed that the “Gear” tab in “Character” cards allows me to define a quantity for each item entry but the same is not true when adding items in the “Cargo Hold” tab of “Vehicle” and “Starship” cards. At the moment, I’m stuck renaming items to add quantity remarks after I add each into Cargo Holad, which is ok but not ideal.

**Comment by madseumas** [comment]
This is actually a problem in the base OpenD6 Space system.  Should be easy to fix, I'll post again once the base system is updated.

**Comment by madseumas** [comment]
Fixed in OpenD6 Space 0.8.2, has been released.

**Comment by UniqueUser97** [comment]
Incredible! Thank you so much for updating this! This is exactly what I was looking for.
