### ISSUE TITLE
Creature Template

### ISSUE THREAD

**Issue by DarthBanjo** [algnc/od6s-star-wars#6]
The creature sheet seems to have some issues with it:
![image](https://user-images.githubusercontent.com/99984933/159031742-af78ab26-5848-4b98-bc4f-a5990209b9e2.png)

**Comment by algnc** [comment]
Will take a look, this was checked in by @madseumas I think.

**Comment by madseumas** [comment]
Odds are I screwed up some CSS in the system on the creature actor header.  I'll dig into it after work today if that's the case.

**Comment by madseumas** [comment]
Yeah, this is a missing opening ```<div>``` in the actor sheet header in the OpenD6 Space ystem itself.  I'll make an issue and get a fix pushed out for it as soon as I can.  @algnc you can probably close this issue here.

**Comment by madseumas** [comment]
Sorry I've been MIA - my primary personal linux workstation bit the dust a few months ago around the same time things heated up at work.  I've finally had the time to resurrect the workstation and work has slowed down.  I'll try to dig into this over this weekend as well.

**Comment by madseumas** [comment]
Should be fixed in the next release.
