### ISSUE TITLE
Character Tabs Content Not Showing

### ISSUE THREAD

**Issue by DarthBanjo** [algnc/od6s-star-wars#7]
The Star Wars od6s style sheet is hiding character tab content for _Inventory, Special Abilities, Biography, & Gear_.  I've noticed it on NPC actors too on the _Gear_ tab. They used to show but perhaps a recent change has broken them. The contents of the tabs show fine when you switch the sheet back to od6s default.
![sheettabshidden](https://user-images.githubusercontent.com/99984933/160969400-d0bb34a7-c438-435e-a78a-0dc9cb0add74.png)

**Comment by algnc** [comment]
This might have broken in a new system update... @madseumas did anything change with these tabs?

**Comment by DarthBanjo** [comment]
Just to narrow down the issue: I think it's related to force powers. If a character is metaphysics extranormal (activating the Force Tab), then the last four tabs show their content normally.

**Comment by madseumas** [comment]
I more than likely did.  I have been swamped but will try to get some time to fix this soon, along with some other reported bugs.

**Comment by DarthBanjo** [comment]
Hey all, just following up to check on this issue. I took a look again and when the star wars sheet is active:
Character actors are missing anything after the Combat tab. 
NPCS and Creatures are missing anything after the combat tab too.

I did a quick count of the string "div" in the metaphysics.html file in src\templates\actor\character\tabs and there are 26 opening divs and 24 closing divs. Maybe with the addition of the star wars sheet's html wrapper something breaks.

**Comment by algnc** [comment]
Well, I thought I found the missing div tags, but it doesn't seem to help. Checking metaphysics extranormal is at least a workaround for now.

**Comment by DarthBanjo** [comment]
Yep, everyone is running around with metaphysics extranormal on as a workaround for now.

**Comment by algnc** [comment]
I will keep working on it this week and see if I can figure it out.

**Comment by madseumas** [comment]
Sorry about the delay, should be fixed in the next release.

**Comment by madseumas** [comment]
Hrm, I thought I'd figured it out, but its looking to be more tricky than I'd thought.  There's something funky happening - if  you look at the elements using debug mode the tabs after combat end up outside the main section/form for the body.   There must have been something with the changes I made to the manifestations tab but my IDE isn't finding anything wrong with the number  of open/closed divs, etc.  I'll keep digging into it until I solve it.

**Comment by madseumas** [comment]
I think this is now fixed in 0.3.4 - there was a missing closing div in the metaphysics actions section on the combat tab.  It makes no sense to me _why_ it fixed it since that section is conditional - there must be something I'm not understanding about handlebars.

**Comment by DarthBanjo** [comment]
Tested and it is fixed! Thank you!
