### ISSUE TITLE
module will not load with relative pathing

### ISSUE THREAD

**Issue by jbowensii** [algnc/od6s-star-wars#8]
For my server configuration, your module fails to load.

I run a ubuntu server in the cloud for about 30 folks, we have 15 games and 15 licenses. 
I know crazy right, and I manage all of the IT Hosting for the group. 

The console shows a 404 : https://MY_SERVER_URL/systems/od6s/module/actor/actor-sheet.js
because it should look for this: https://MY_SERVER_URL/game12/systems/od6s/module/actor/actor-sheet.js

In the foundry configuration I set the "routePrefix": "game12" which allows for my configuration.

./module/actor-sheets-star-wars.js  has this line: 
     import OD6SActorSheet from '/systems/od6s/module/actor/actor-sheet.js'

looking at tidy5e sheet for D&D 5e... you have to use relative paths to make sure and honor any pathing done on the hosting machine

this change fixes the issue:
     import OD6SActorSheet from '../../../systems/od6s/module/actor/actor-sheet.js'

Would you mind doing this ... thank you

**Comment by algnc** [comment]
Fixed in #9
